import { Injectable } from '@nestjs/common';
import {
  DailyNutritionTarget,
  HEALTH_FLAGS,
  HealthFlag,
  NutritionTargetMethodology,
  User,
} from '@calorie-ai/types';

const ALGORITHM_VERSION = 'daily-nutrition-v4';
const CLINICIAN_FLAGS: HealthFlag[] = [
  'pregnant',
  'breastfeeding',
  'kidney_disease',
  'eating_disorder_history',
];

@Injectable()
export class NutritionRecommendationEngine {
  calculate(
    profile: Partial<User> | null | undefined,
    date: string,
    calorieTarget?: number,
  ): DailyNutritionTarget {
    const healthFlags = this.healthFlags(profile?.health_flags);
    const missingFields = [
      !this.positive(profile?.age) ? 'age' : null,
      !profile?.gender ? 'gender' : null,
      !this.positive(profile?.weight_kg) ? 'weight_kg' : null,
      !profile?.activity_level ? 'activity_level' : null,
      !profile?.goal ? 'goal' : null,
      !this.positive(calorieTarget ?? profile?.daily_calorie_target) ? 'daily_calorie_target' : null,
    ].filter((field): field is string => Boolean(field));
    const base = {
      date,
      rationale: {},
      factors: {
        age: profile?.age,
        weight_kg: profile?.weight_kg,
        activity_level: profile?.activity_level,
        work_activity_level: profile?.work_activity_level,
        exercise_sessions_per_week: profile?.exercise_sessions_per_week,
        exercise_minutes_per_session: profile?.exercise_minutes_per_session,
        sweat_level: profile?.sweat_level,
        climate_exposure: profile?.climate_exposure,
        goal: profile?.goal,
        health_flags: healthFlags,
      },
      missing_fields: missingFields,
      warnings: [] as string[],
      evidence: this.evidence(profile),
      methodology: {},
      calculated_at: new Date().toISOString(),
      algorithm_version: ALGORITHM_VERSION,
    };

    const clinicianTarget = this.clinicianTarget(profile);
    if (clinicianTarget) {
      const verified = clinicianTarget.provenance === 'provider_verified'
        && clinicianTarget.verification_status === 'verified'
        && Boolean(clinicianTarget.verified_at)
        && Boolean(clinicianTarget.verified_by);
      const provenanceLabel = verified ? 'verified provider plan' : 'user-reported clinician plan';
      const reason = clinicianTarget.reason ?? `Uses ${provenanceLabel} from ${clinicianTarget.source}.`;
      return {
        ...base,
        status: 'clinician_target',
        calories_kcal: clinicianTarget.calories_kcal,
        protein_g: clinicianTarget.protein_g,
        carbs_g: clinicianTarget.carbs_g,
        fat_g: clinicianTarget.fat_g,
        fiber_g: clinicianTarget.fiber_g,
        water_ml: clinicianTarget.water_ml,
        sodium_mg_max: clinicianTarget.sodium_mg_max,
        rationale: { calories: reason, protein: reason, water: reason },
        methodology: this.clinicianMethodology(clinicianTarget),
        warnings: [
          'Targets were entered from a clinician plan and were not generated by the general formula.',
          ...(verified ? [] : ['This plan was reported and confirmed by the user; Calorie AI has not independently verified the provider or document.']),
        ],
      };
    }

    if (missingFields.length > 0) {
      return { ...base, status: 'needs_profile' };
    }

    if ((profile?.age ?? 0) < 18 || healthFlags.some((flag) => CLINICIAN_FLAGS.includes(flag))) {
      return {
        ...base,
        status: 'clinician_guidance',
        warnings: [
          'Nutrition targets require age- or condition-specific clinical guidance and were not generated from the general adult formula.',
        ],
      };
    }

    const calories = Math.round(calorieTarget ?? profile!.daily_calorie_target!);
    const weightKg = Number(profile!.weight_kg);
    const proteinMultiplier = this.proteinMultiplier(profile!);
    const protein = Math.round(weightKg * proteinMultiplier);
    const fatEnergyPct = 25;
    const fat = Math.round((calories * fatEnergyPct / 100) / 9);
    const carbs = Math.max(0, Math.round((calories - protein * 4 - fat * 9) / 4));
    const activityWater = profile!.activity_level === 'very_active'
      ? 500
      : profile!.activity_level === 'active' ? 250 : 0;
    const sweatWater = profile!.sweat_level === 'high'
      ? 500
      : profile!.sweat_level === 'moderate' ? 250 : 0;
    const climateWater = profile!.climate_exposure === 'extreme_heat'
      ? 500
      : profile!.climate_exposure === 'hot_humid' ? 250 : 0;
    const water = Math.round(Math.min(4500, Math.max(1500, weightKg * 32.5 + activityWater + sweatWater + climateWater)) / 50) * 50;
    const warnings = [
      'Targets are general wellness estimates, not medical diagnosis or treatment.',
      ...(healthFlags.includes('diabetes')
        ? ['Diabetes requires individualized carbohydrate and glucose guidance; this target is not a treatment plan.']
        : []),
      ...(healthFlags.includes('weight_affecting_medication')
        ? ['Weight-affecting medication can change energy needs; review targets with a qualified clinician.']
        : []),
    ];

    return {
      ...base,
      status: 'ready',
      calories_kcal: calories,
      protein_g: protein,
      carbs_g: carbs,
      fat_g: fat,
      fiber_g: Math.round((calories / 1000) * 14),
      water_ml: water,
      sodium_mg_max: 2000,
      free_sugar_g_max: Math.round((calories * 0.1) / 4),
      saturated_fat_g_max: Math.round((calories * 0.1) / 9),
      rationale: {
        calories: 'Uses the active daily calorie target calculated from profile and goal.',
        protein: this.proteinReason(profile!, proteinMultiplier),
        carbs: 'Receives remaining energy after protein and a 25% fat allocation.',
        fat: 'Uses 25% of daily energy as a general adult baseline.',
        fiber: 'Uses 14 g per 1000 kcal.',
        water: 'Uses a 32.5 ml/kg practical midpoint within the common 30–35 ml/kg range, plus activity, reported sweat, and typical climate-exposure adjustments.',
      },
      factors: {
        ...base.factors,
        protein_g_per_kg: proteinMultiplier,
        fat_energy_pct: fatEnergyPct,
      },
      warnings,
      methodology: this.generalMethodology(),
    };
  }

  private generalMethodology(): DailyNutritionTarget['methodology'] {
    return {
      calories_kcal: {
        method: 'Uses the active calorie target produced by the calorie-target service.',
        evidence_level: 'evidence_informed_heuristic',
        evidence_ids: ['niddk-body-weight-planner'],
        assumptions: ['Profile activity and food logging are approximate.', 'The target is recalculated when profile inputs change.'],
        is_user_adjustable: false,
      },
      protein_g: {
        method: 'Body weight multiplied by an activity-, goal-, age-, and athlete-adjusted recommendation factor.',
        evidence_level: 'evidence_informed_heuristic',
        evidence_ids: ['efsa-protein-drv-2012', 'prot-age-2013', 'issn-protein-exercise-2017', 'morton-protein-meta-2018'],
        assumptions: ['The exact activity ladder is a product rule assembled from population ranges.', 'Recommendation caps are not tolerable upper intake limits.'],
        is_user_adjustable: false,
      },
      fat_g: {
        method: 'Defaults to 25% of daily energy.',
        evidence_level: 'guideline_range_with_product_default',
        evidence_ids: ['efsa-drv-fat-water-2010'],
        assumptions: ['25% is a product default inside the adult 20–35% reference range.'],
        is_user_adjustable: true,
        reference_range: { min: 20, max: 35, unit: '% energy' },
      },
      carbs_g: {
        method: 'Receives remaining energy after protein and the default fat allocation, using 4 kcal/g.',
        evidence_level: 'evidence_informed_heuristic',
        evidence_ids: ['efsa-drv-fat-water-2010'],
        assumptions: ['This is an energy allocation, not an individualized diabetes treatment target.'],
        is_user_adjustable: true,
      },
      fiber_g: {
        method: '14 g per 1000 kcal.',
        evidence_level: 'guideline',
        evidence_ids: ['usda-dri-calculator'],
        assumptions: ['General wellness target; gastrointestinal tolerance can differ.'],
        is_user_adjustable: true,
      },
      water_ml: {
        method: '32.5 ml/kg midpoint baseline plus fixed activity, reported-sweat, and climate-exposure adjustments, rounded to 50 ml.',
        evidence_level: 'evidence_informed_heuristic',
        evidence_ids: ['efsa-drv-fat-water-2010', 'national-academies-water-2005'],
        assumptions: ['32.5 ml/kg and the +250/+500 ml climate steps are product heuristics, not EFSA/National Academies formulas.', 'Climate exposure is user-reported and does not use live weather.', 'Does not yet model altitude, food moisture, illness, medication, or measured sweat loss.'],
        is_user_adjustable: true,
        is_product_guardrail: true,
        reference_range: { min: 1500, max: 4500, unit: 'ml/day product guardrail' },
      },
      sodium_mg_max: {
        method: 'General adult maximum of 2000 mg sodium per day.',
        evidence_level: 'guideline',
        evidence_ids: ['who-healthy-diet'],
        assumptions: ['Children and clinical conditions require individualized limits.'],
        is_user_adjustable: true,
      },
      free_sugar_g_max: {
        method: 'Less than 10% of daily energy, converted at 4 kcal/g.',
        evidence_level: 'guideline',
        evidence_ids: ['who-healthy-diet'],
        assumptions: ['Applies to free sugar, not total naturally occurring sugar.'],
        is_user_adjustable: true,
        reference_range: { max: 10, unit: '% energy' },
      },
      saturated_fat_g_max: {
        method: 'Less than 10% of daily energy, converted at 9 kcal/g.',
        evidence_level: 'guideline',
        evidence_ids: ['who-healthy-diet'],
        assumptions: ['General population prevention target.'],
        is_user_adjustable: true,
        reference_range: { max: 10, unit: '% energy' },
      },
    };
  }

  private clinicianMethodology(
    target: Record<string, unknown>,
  ): DailyNutritionTarget['methodology'] {
    const methodology: DailyNutritionTarget['methodology'] = {};
    const keys = [
      'calories_kcal',
      'protein_g',
      'carbs_g',
      'fat_g',
      'fiber_g',
      'water_ml',
      'sodium_mg_max',
    ] as const;
    const item: NutritionTargetMethodology = {
      method: target.verification_status === 'verified' && target.provenance === 'provider_verified'
        ? `Provider-verified clinician plan from ${String(target.source)}.`
        : `User-reported clinician plan from ${String(target.source)}.`,
      evidence_level: 'clinician_target',
      evidence_ids: [],
      assumptions: [
        'Validity depends on the supplied clinical plan and its review date.',
        ...(target.verification_status === 'verified' && target.provenance === 'provider_verified'
          ? []
          : ['Provider identity and source document have not been independently verified by Calorie AI.']),
      ],
      is_user_adjustable: false,
    };
    for (const key of keys) {
      if (this.positive(target[key])) methodology[key] = { ...item };
    }
    return methodology;
  }

  private proteinMultiplier(profile: Partial<User>): number {
    const activityBase = {
      sedentary: 1.0,
      light: 1.1,
      moderate: 1.2,
      active: 1.4,
      very_active: 1.6,
    }[profile.activity_level ?? 'sedentary'];
    let multiplier = activityBase;
    if (profile.goal === 'lose_weight') multiplier = Math.max(multiplier, 1.4);
    if (profile.goal === 'gain_muscle') multiplier = Math.max(multiplier, 1.6);
    if ((profile.age ?? 0) >= 65) multiplier = Math.max(multiplier, 1.2);
    if (profile.athlete_level === 'competitive') multiplier = Math.max(multiplier, 1.4);
    if (profile.athlete_level === 'elite') multiplier = Math.max(multiplier, 1.6);
    const cap = profile.athlete_level
      ? 2.0
      : profile.goal === 'gain_muscle' ? 2.2 : profile.goal === 'lose_weight' ? 1.8 : (profile.age ?? 0) >= 65 ? 1.5 : 1.6;
    return Math.min(multiplier, cap);
  }

  private proteinReason(profile: Partial<User>, multiplier: number): string {
    const factors = [
      `${profile.goal ?? 'maintain'} goal`,
      `${profile.activity_level ?? 'sedentary'} activity`,
      ...(profile.athlete_level ? [`${profile.athlete_level} athlete`] : []),
      ...((profile.age ?? 0) >= 65 ? ['older-adult baseline'] : []),
    ];
    return `${multiplier.toFixed(1)} g/kg based on ${factors.join(', ')}.`;
  }

  private healthFlags(flags?: HealthFlag[]): HealthFlag[] {
    if (!Array.isArray(flags)) return [];
    return [...new Set(flags.filter((flag): flag is HealthFlag => HEALTH_FLAGS.includes(flag)))];
  }

  private clinicianTarget(profile: Partial<User> | null | undefined) {
    const target = profile?.clinician_nutrition_targets;
    if (!target?.source?.trim()) return null;
    if (target.status !== 'active' || !target.confirmed_at) return null;
    if (target.expires_at && new Date(target.expires_at).getTime() < Date.now()) return null;
    const numericKeys = [
      'calories_kcal',
      'protein_g',
      'carbs_g',
      'fat_g',
      'fiber_g',
      'water_ml',
      'sodium_mg_max',
    ] as const;
    const sanitized = Object.fromEntries(
      numericKeys
        .map((key) => [key, Number(target[key])])
        .filter(([, value]) => Number.isFinite(value) && Number(value) > 0),
    );
    if (Object.keys(sanitized).length === 0) return null;
    return { ...target, ...sanitized };
  }

  private evidence(profile: Partial<User> | null | undefined) {
    const flags = this.healthFlags(profile?.health_flags);
    const evidence = [{
      id: 'usda-dri-calculator',
      organization: 'USDA / National Academies',
      title: 'Dietary Reference Intakes Calculator for Healthcare Professionals',
      url: 'https://www.nal.usda.gov/fnic/dri-calculator/',
      applies_to: ['general', 'children', 'pregnancy', 'breastfeeding'],
      evidence_level: 'guideline' as const,
    }, {
      id: 'efsa-protein-drv-2012',
      organization: 'European Food Safety Authority',
      title: 'Population reference intakes for protein',
      url: 'https://www.efsa.europa.eu/en/press/news/120209',
      applies_to: ['general', 'protein'],
      evidence_level: 'guideline' as const,
    }, {
      id: 'efsa-drv-fat-water-2010',
      organization: 'European Food Safety Authority',
      title: 'Dietary reference values for fats and water',
      url: 'https://www.efsa.europa.eu/en/press/news/nda100326',
      applies_to: ['fat', 'water', 'carbohydrate'],
      evidence_level: 'guideline' as const,
    }, {
      id: 'who-healthy-diet',
      organization: 'World Health Organization',
      title: 'Healthy diet',
      url: 'https://www.who.int/news-room/fact-sheets/detail/healthy-diet',
      applies_to: ['sodium', 'free_sugar', 'saturated_fat'],
      evidence_level: 'guideline' as const,
    }, {
      id: 'national-academies-water-2005',
      organization: 'National Academies',
      title: 'Dietary Reference Intakes for Water, Potassium, Sodium, Chloride, and Sulfate',
      url: 'https://nap.nationalacademies.org/catalog/10925/dietary-reference-intakes-for-water-potassium-sodium-chloride-and-sulfate',
      applies_to: ['water'],
      evidence_level: 'guideline' as const,
    }, {
      id: 'niddk-body-weight-planner',
      organization: 'NIDDK',
      title: 'Research Behind the Body Weight Planner',
      url: 'https://www.niddk.nih.gov/research-funding/at-niddk/labs-branches/laboratory-biological-modeling/integrative-physiology-section/research/body-weight-planner',
      applies_to: ['energy', 'weight_change'],
      evidence_level: 'validated_equation' as const,
    }];
    if ((profile?.age ?? 0) >= 65) evidence.push({
      id: 'prot-age-2013',
      organization: 'PROT-AGE Study Group',
      title: 'Evidence-based recommendations for optimal dietary protein intake in older people',
      url: 'https://pubmed.ncbi.nlm.nih.gov/23867520/',
      applies_to: ['older_adults', 'protein'],
      evidence_level: 'guideline' as const,
    });
    if (profile?.athlete_level) evidence.push({
      id: 'issn-protein-exercise-2017',
      organization: 'International Society of Sports Nutrition',
      title: 'Position Stand: protein and exercise',
      url: 'https://pubmed.ncbi.nlm.nih.gov/28642676/',
      applies_to: ['athletes', 'protein'],
      evidence_level: 'guideline' as const,
    });
    if (profile?.goal === 'gain_muscle' || profile?.athlete_level) evidence.push({
      id: 'morton-protein-meta-2018',
      organization: 'British Journal of Sports Medicine',
      title: 'Protein supplementation and resistance training meta-analysis',
      url: 'https://pubmed.ncbi.nlm.nih.gov/28698222/',
      applies_to: ['resistance_training', 'protein'],
      evidence_level: 'validated_equation' as const,
    });
    if (flags.includes('pregnant')) evidence.push({
      id: 'cdc-pregnancy-calories',
      organization: 'CDC',
      title: 'Weight Gain During Pregnancy',
      url: 'https://www.cdc.gov/maternal-infant-health/pregnancy-weight/index.html',
      applies_to: ['pregnancy', 'energy'],
      evidence_level: 'guideline' as const,
    });
    if (flags.includes('breastfeeding')) evidence.push({
      id: 'cdc-breastfeeding-diet',
      organization: 'CDC',
      title: 'Maternal Diet and Breastfeeding',
      url: 'https://www.cdc.gov/breastfeeding-special-circumstances/hcp/diet-micronutrients/maternal-diet.html',
      applies_to: ['breastfeeding', 'energy'],
      evidence_level: 'guideline' as const,
    });
    if (flags.includes('kidney_disease')) evidence.push({
      id: 'niddk-ckd-nutrition',
      organization: 'NIDDK',
      title: 'Healthy Eating for Adults with Chronic Kidney Disease',
      url: 'https://www.niddk.nih.gov/health-information/kidney-disease/chronic-kidney-disease-ckd/eating-nutrition',
      applies_to: ['kidney_disease', 'protein', 'sodium'],
      evidence_level: 'guideline' as const,
    });
    if (flags.includes('diabetes')) evidence.push({
      id: 'ada-standards-care',
      organization: 'American Diabetes Association',
      title: 'Standards of Care in Diabetes',
      url: 'https://professional.diabetes.org/standards-of-care/practice-guidelines-resources',
      applies_to: ['diabetes', 'carbohydrate'],
      evidence_level: 'guideline' as const,
    });
    if (flags.includes('eating_disorder_history')) evidence.push({
      id: 'nimh-eating-disorders',
      organization: 'NIMH',
      title: 'Eating Disorders: What You Need to Know',
      url: 'https://www.nimh.nih.gov/health/publications/eating-disorders',
      applies_to: ['eating_disorders', 'clinical_care'],
      evidence_level: 'guideline' as const,
    });
    return evidence;
  }

  private positive(value: unknown): boolean {
    return Number.isFinite(Number(value)) && Number(value) > 0;
  }
}
