name: Secret scan on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run secret scan script
        run: |
          node ./scripts/find_potential_secrets.js
